# see
#   http://about.travis-ci.org/docs/user/getting-started/
#   http://about.travis-ci.org/docs/user/languages/c/
#   http://about.travis-ci.org/docs/user/build-configuration/
#
language: c
compiler:
  - gcc
  - clang
script: ./autogen.sh && make && make test
